/** Theme tokens are defined as CSS HSL channels and shared by light/dark modes. */
const withVar = (name) => `hsl(var(--color-${name}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx,css}'],
  theme: {
    extend: {
      colors: {
        'brand-primary': withVar('brand-primary'),
        'brand-accent': withVar('brand-accent'),
        'brand-muted': withVar('brand-muted'),
        'surface-base': withVar('surface-base'),
        'surface-warm': withVar('surface-warm'),
        'surface-sunken': withVar('surface-sunken'),
        'surface-raised': withVar('surface-raised'),
        'surface-glass': withVar('surface-glass'),
        'sidebar': withVar('sidebar'),
        'sidebar-hover': withVar('sidebar-hover'),
        'sidebar-border': withVar('sidebar-border'),
        'text-primary': withVar('text-primary'),
        'text-secondary': withVar('text-secondary'),
        'text-tertiary': withVar('text-tertiary'),
        'text-muted': withVar('text-muted'),
        'text-inverse': withVar('text-inverse'),
        'text-on-sidebar': withVar('text-on-sidebar'),
        'text-on-sidebar-active': withVar('text-on-sidebar-active'),
        'border-subtle': withVar('border-subtle'),
        'border-strong': withVar('border-strong'),
        'status-success': withVar('status-success'),
        'status-warning': withVar('status-warning'),
        'status-error': withVar('status-error'),
        'status-info': withVar('status-info'),
        'status-standby': withVar('status-standby'),
        'identity-1': withVar('identity-1'),
        'identity-2': withVar('identity-2'),
        'identity-3': withVar('identity-3'),
        'identity-4': withVar('identity-4'),
        'identity-5': withVar('identity-5'),
        'identity-6': withVar('identity-6'),
        'identity-7': withVar('identity-7'),
        'identity-8': withVar('identity-8'),
      },
      fontSize: {
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        body: ['14px', { lineHeight: '1.55', letterSpacing: '0em' }],
        'body-lg': ['17px', { lineHeight: '1.5', letterSpacing: '0em' }],
        h3: ['20px', { lineHeight: '1.3', letterSpacing: '-0.005em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        h1: ['29px', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        display: ['42px', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      fontFamily: {
        body: ['chironHeiHK', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'sans-serif'],
        zh: ['chironHeiHK', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'sans-serif'],
      },
      spacing: {
        micro: '4px',
        tight: '8px',
        snug: '12px',
        base: '16px',
        comfortable: '24px',
        'stack-sm': '24px',
        'stack-md': '32px',
        loose: '32px',
        section: '64px',
        'stack-lg': '64px',
        'section-y': '96px',
        macro: '128px',
      },
      borderRadius: {
        sm: '6px',
        md: '6px',
        lg: '8px',
        card: '8px',
        xl: '12px',
        button: '6px',
        input: '6px',
      },
      boxShadow: {
        'level-1': 'var(--shadow-level-1)',
        'level-2': 'var(--shadow-level-2)',
        'level-3': 'var(--shadow-level-3)',
        'level-4': 'var(--shadow-level-4)',
        card: 'var(--shadow-level-1)',
      },
      transitionDuration: {
        motionFast: '140ms',
        motion: '220ms',
        motionSlow: '360ms',
      },
    },
  },
  plugins: [],
};
