/**
 * IntelliJ ExpUI Light editor scheme → Monaco theme.
 * Source: JetBrains/intellij-community
 *   platform/platform-resources/src/themes/expUI/expUI_lightScheme.xml
 *   platform/platform-resources/src/themes/expUI/expUI_light.theme.json
 */
import type { editor } from 'monaco-editor'

/** Semantic / syntax colors from expUI_lightScheme.xml (DEFAULT_* / PROPERTIES.*). */
export const IdeaColors = {
  text: '#080808',
  background: '#FFFFFF',
  caretRow: '#F5F8FE',
  selection: '#A6D2FF',
  lineNumber: '#AEB3C2',
  lineNumberActive: '#767A8A',
  indentGuide: '#EBECF0',
  keyword: '#0033B3',
  string: '#067D17',
  stringEscape: '#0037A6',
  number: '#1750EB',
  comment: '#8C8C8C',
  docTagValue: '#3D3D3D',
  metadata: '#9E880D',
  instanceField: '#871094',
  staticField: '#871094',
  constant: '#871094',
  functionDecl: '#00627A',
  typeParam: '#007E8A',
  attribute: '#174AD4',
  entity: '#174BE6',
  propertiesKey: '#083080',
  yamlAnchor: '#0000E6',
  hyperlink: '#006DCC',
  wrongRef: '#F50000',
} as const

/** New UI chrome palette (expUI_light.theme.json colors). */
export const ExpUI = {
  Gray1: '#000000',
  Gray5: '#5A5D6B',
  Gray6: '#6C707E',
  Gray7: '#818594',
  Gray8: '#A8ADBD',
  Gray9: '#C9CCD6',
  Gray10: '#D3D5DB',
  Gray11: '#DFE1E5',
  Gray12: '#EBECF0',
  Gray13: '#F7F8FA',
  Gray14: '#FFFFFF',
  Blue4: '#3574F0',
  Blue11: '#D4E2FF',
  Blue12: '#EDF3FF',
  Blue13: '#F5F8FE',
  Green5: '#369650',
  Green10: '#E3F7E7',
  Red4: '#DB3B4B',
} as const

export const ideaLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: IdeaColors.text.slice(1) },
    { token: 'comment', foreground: IdeaColors.comment.slice(1), fontStyle: 'italic' },
    { token: 'comment.doc', foreground: IdeaColors.comment.slice(1), fontStyle: 'italic' },
    { token: 'keyword', foreground: IdeaColors.keyword.slice(1) },
    { token: 'storage', foreground: IdeaColors.keyword.slice(1) },
    { token: 'string', foreground: IdeaColors.string.slice(1) },
    { token: 'string.escape', foreground: IdeaColors.stringEscape.slice(1) },
    { token: 'number', foreground: IdeaColors.number.slice(1) },
    { token: 'regexp', foreground: '264EFF' },
    { token: 'type', foreground: IdeaColors.text.slice(1) },
    { token: 'type.identifier', foreground: IdeaColors.text.slice(1) },
    { token: 'delimiter', foreground: IdeaColors.text.slice(1) },
    { token: 'delimiter.java', foreground: IdeaColors.text.slice(1) },
    { token: 'annotation', foreground: IdeaColors.metadata.slice(1) },
    { token: 'annotation.java', foreground: IdeaColors.metadata.slice(1) },
    { token: 'tag', foreground: IdeaColors.keyword.slice(1) },
    { token: 'metatag', foreground: IdeaColors.metadata.slice(1) },
    { token: 'attribute.name', foreground: IdeaColors.attribute.slice(1) },
    { token: 'attribute.value', foreground: IdeaColors.string.slice(1) },
    { token: 'attribute.value.number', foreground: IdeaColors.number.slice(1) },
    { token: 'attribute.value.unit', foreground: IdeaColors.number.slice(1) },
    { token: 'attribute.value.html', foreground: IdeaColors.string.slice(1) },
    { token: 'attribute.value.xml', foreground: IdeaColors.string.slice(1) },
    { token: 'tag.xml', foreground: IdeaColors.keyword.slice(1) },
    { token: 'metatag.xml', foreground: IdeaColors.metadata.slice(1) },
    // YAML: Monaco marks keys as `type`
    { token: 'type.yaml', foreground: IdeaColors.propertiesKey.slice(1) },
    { token: 'string.yaml', foreground: IdeaColors.string.slice(1) },
    { token: 'number.yaml', foreground: IdeaColors.number.slice(1) },
    { token: 'keyword.yaml', foreground: IdeaColors.keyword.slice(1) },
    { token: 'comment.yaml', foreground: IdeaColors.comment.slice(1), fontStyle: 'italic' },
    // Custom properties language
    { token: 'key.properties', foreground: IdeaColors.propertiesKey.slice(1) },
    { token: 'value.properties', foreground: IdeaColors.text.slice(1) },
    { token: 'comment.properties', foreground: IdeaColors.comment.slice(1), fontStyle: 'italic' },
    { token: 'separator.properties', foreground: IdeaColors.text.slice(1) },
    // JSON
    { token: 'string.key.json', foreground: IdeaColors.propertiesKey.slice(1) },
    { token: 'string.value.json', foreground: IdeaColors.string.slice(1) },
    { token: 'number.json', foreground: IdeaColors.number.slice(1) },
    { token: 'keyword.json', foreground: IdeaColors.keyword.slice(1) },
    // Markdown
    { token: 'keyword.md', foreground: IdeaColors.keyword.slice(1) },
    { token: 'string.md', foreground: IdeaColors.string.slice(1) },
    { token: 'variable.md', foreground: IdeaColors.instanceField.slice(1) },
  ],
  colors: {
    'editor.background': IdeaColors.background,
    'editor.foreground': IdeaColors.text,
    'editor.lineHighlightBackground': IdeaColors.caretRow,
    'editor.selectionBackground': IdeaColors.selection,
    'editor.inactiveSelectionBackground': '#A6D2FF66',
    'editor.findMatchBackground': '#FFEAA866',
    'editor.findMatchHighlightBackground': '#FFEAA844',
    'editorLineNumber.foreground': IdeaColors.lineNumber,
    'editorLineNumber.activeForeground': IdeaColors.lineNumberActive,
    'editorGutter.background': IdeaColors.background,
    'editorIndentGuide.background1': IdeaColors.indentGuide,
    'editorIndentGuide.activeBackground1': '#AEB3C2',
    'editorCursor.foreground': '#000000',
    'editorWhitespace.foreground': '#D3D5DB',
    'editorBracketMatch.background': '#62B3B333',
    'editorBracketMatch.border': '#62B3B3',
    'editorWidget.background': ExpUI.Gray14,
    'editorWidget.border': ExpUI.Gray10,
    'editorSuggestWidget.background': ExpUI.Gray14,
    'editorSuggestWidget.border': ExpUI.Gray10,
    'editorSuggestWidget.selectedBackground': ExpUI.Blue11,
    'scrollbarSlider.background': '#C9CCD680',
    'scrollbarSlider.hoverBackground': '#A8ADBD99',
    'scrollbarSlider.activeBackground': '#818594AA',
  },
}

/** A dark companion for the embedded workbench theme bridge. */
export const ideaDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'D4D7E0' },
    { token: 'comment', foreground: '7F8799', fontStyle: 'italic' },
    { token: 'keyword', foreground: '6EA8FE' },
    { token: 'storage', foreground: '6EA8FE' },
    { token: 'string', foreground: '8FD694' },
    { token: 'string.escape', foreground: '8AB4F8' },
    { token: 'number', foreground: '8AB4F8' },
    { token: 'annotation', foreground: 'D7BA7D' },
    { token: 'annotation.java', foreground: 'D7BA7D' },
    { token: 'type', foreground: 'D4D7E0' },
    { token: 'type.identifier', foreground: 'D4D7E0' },
    { token: 'attribute.name', foreground: '8AB4F8' },
    { token: 'attribute.value', foreground: '8FD694' },
    { token: 'key.properties', foreground: 'B9A6FF' },
    { token: 'value.properties', foreground: 'D4D7E0' },
    { token: 'keyword.md', foreground: '6EA8FE' },
    { token: 'string.md', foreground: '8FD694' },
  ],
  colors: {
    'editor.background': '#1F232B',
    'editor.foreground': '#D4D7E0',
    'editor.lineHighlightBackground': '#252B35',
    'editor.selectionBackground': '#264F78',
    'editor.inactiveSelectionBackground': '#264F7866',
    'editor.findMatchBackground': '#80600088',
    'editor.findMatchHighlightBackground': '#80600044',
    'editorLineNumber.foreground': '#6F7787',
    'editorLineNumber.activeForeground': '#B8BFCC',
    'editorGutter.background': '#1F232B',
    'editorIndentGuide.background1': '#343B48',
    'editorIndentGuide.activeBackground1': '#596476',
    'editorCursor.foreground': '#D4D7E0',
    'editorWhitespace.foreground': '#454D5C',
    'editorBracketMatch.background': '#3D6B6B55',
    'editorBracketMatch.border': '#69B8B8',
    'editorWidget.background': '#292F3A',
    'editorWidget.border': '#454D5C',
    'editorSuggestWidget.background': '#292F3A',
    'editorSuggestWidget.border': '#454D5C',
    'editorSuggestWidget.selectedBackground': '#344D70',
    'scrollbarSlider.background': '#59647680',
    'scrollbarSlider.hoverBackground': '#7A849799',
    'scrollbarSlider.activeBackground': '#9AA5B8AA',
  },
}
