#!/usr/bin/env bash
#
# generate.sh - materialise the synthetic multi-repository Java fixture used by the
# unified project knowledge library tests.
#
# Usage:
#   bash generate.sh [target-dir]
#
# target-dir defaults to "$PWD/.agent-work/knowledge-fixtures". The target directory is
# DELETED and recreated on every run.
#
# The generator is deterministic and idempotent: every fixture commit uses a fixed
# author/committer identity, a fixed timestamp and fixed commit messages, so repeated
# runs into different directories produce identical commit SHAs and byte-identical
# fixture-manifest.json files (the only environment-dependent value in the manifest is
# the absolute repository path).
#
# Generated layout:
#   <target>/common           shared contract library, released as com.example:common:1.4.2
#   <target>/order-service    publishes OrderCancelledEvent, depends on common 1.4.2
#   <target>/device-service   consumes OrderCancelledEvent, depends on common 2.0.0
#   <target>/fixture-manifest.json
#
# Determinism rail: the fixture repositories intentionally have no .gitignore, and the
# global/system git configuration (including core.excludesFile, commit.gpgsign and any
# init.defaultBranch) is neutralised below so that commit SHAs do not depend on the
# machine that runs the generator.

set -euo pipefail

FIXED_DATE='2026-01-02T03:04:05+00:00'
FIXED_GENERATED_AT='2026-01-02T03:04:05+00:00'
MANIFEST_NOTES='Synthetic fixture material generated by testdata/knowledge-fixtures/generate.sh for knowledge-library tests. It is not real project data, is not derived from any production repository, and must not be treated as project truth.'

TARGET="${1:-$PWD/.agent-work/knowledge-fixtures}"

case "$TARGET" in
  ''|'/'|'.'|'..')
    printf 'generate.sh: refusing to use %s as the fixture target\n' "${TARGET:-<empty>}" >&2
    exit 2
    ;;
esac
if [ -e "$TARGET/.git" ]; then
  printf 'generate.sh: refusing to delete %s because it contains a .git directory\n' "$TARGET" >&2
  exit 2
fi

umask 022

# Deterministic git environment: fixed identity, fixed timestamps, no ambient config.
export GIT_AUTHOR_NAME=fixture
export GIT_AUTHOR_EMAIL=fixture@example.invalid
export GIT_AUTHOR_DATE="$FIXED_DATE"
export GIT_COMMITTER_NAME=fixture
export GIT_COMMITTER_EMAIL=fixture@example.invalid
export GIT_COMMITTER_DATE="$FIXED_DATE"
export GIT_CONFIG_NOSYSTEM=1
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_TERMINAL_PROMPT=0
export TZ=UTC
export LC_ALL=C

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

init_repo() {
  local repo="$1"
  mkdir -p "$repo"
  if ! git -C "$repo" init -q -b main >/dev/null 2>&1; then
    # git < 2.28 has no "init -b".
    git -C "$repo" init -q >/dev/null 2>&1
    git -C "$repo" symbolic-ref HEAD refs/heads/main
  fi
  git -C "$repo" config user.name fixture
  git -C "$repo" config user.email fixture@example.invalid
  git -C "$repo" config core.autocrlf false
  git -C "$repo" config core.safecrlf false
  git -C "$repo" config core.excludesFile /dev/null
  git -C "$repo" config commit.gpgsign false
  git -C "$repo" config tag.gpgsign false
  git -C "$repo" config advice.detachedHead false
}

commit_repo() {
  local repo="$1"
  local message="$2"
  git -C "$repo" add -A
  GIT_AUTHOR_NAME=fixture \
  GIT_AUTHOR_EMAIL=fixture@example.invalid \
  GIT_AUTHOR_DATE="$FIXED_DATE" \
  GIT_COMMITTER_NAME=fixture \
  GIT_COMMITTER_EMAIL=fixture@example.invalid \
  GIT_COMMITTER_DATE="$FIXED_DATE" \
    git -C "$repo" commit -q -m "$message"
}

json_string() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

untracked_json_array() {
  local repo="$1"
  local out=''
  local line
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    out="${out}${out:+, }$(json_string "$line")"
  done < <(git -C "$repo" ls-files --others --exclude-standard | LC_ALL=C sort)
  printf '[%s]' "$out"
}

MANIFEST_REPOS=''
REPO_INDEX=0

emit_repo() {
  local name="$1"
  local kind="$2"
  local artifact="$3"
  local consumer="$4"
  local repo="$TARGET/$name"
  local head branch count status_out dirty untracked_json

  head="$(git -C "$repo" rev-parse HEAD)"
  branch="$(git -C "$repo" rev-parse --abbrev-ref HEAD)"
  count="$(git -C "$repo" rev-list --count HEAD)"
  status_out="$(git -C "$repo" status --porcelain)"
  if [ -n "$status_out" ]; then
    dirty=true
  else
    dirty=false
  fi
  untracked_json="$(untracked_json_array "$repo")"

  REPO_INDEX=$((REPO_INDEX + 1))
  if [ "$REPO_INDEX" -gt 1 ]; then
    MANIFEST_REPOS="${MANIFEST_REPOS},"
  fi
  MANIFEST_REPOS="${MANIFEST_REPOS}
    {
      \"name\": $(json_string "$name"),
      \"kind\": $(json_string "$kind"),
      \"path\": $(json_string "$repo"),
      \"branch\": $(json_string "$branch"),
      \"head_commit\": $(json_string "$head"),
      \"commit_count\": ${count},
      \"dirty\": ${dirty},
      \"untracked\": ${untracked_json},
      \"artifact\": $(json_string "$artifact"),
      \"consumer\": $(json_string "$consumer")
    }"
}

rm -rf -- "$TARGET"
mkdir -p -- "$TARGET"

COMMON="$TARGET/common"
ORDER="$TARGET/order-service"
DEVICE="$TARGET/device-service"

##############################################################################
# common - shared contract library (kind: common)
##############################################################################

init_repo "$COMMON"

write_file "$COMMON/pom.xml" <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>common</artifactId>
  <version>1.4.2</version>
  <packaging>jar</packaging>

  <name>common</name>
  <description>Shared domain contracts and messaging ports used by the example services.</description>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.13</version>
    </dependency>
  </dependencies>
</project>
XML

write_file "$COMMON/src/main/java/com/example/common/event/OrderCancelledEvent.java" <<'JAVA'
package com.example.common.event;

import java.time.Instant;
import java.util.Objects;

/**
 * Domain event published when an order is cancelled.
 *
 * <p>This type is the shared contract between order-service (producer) and
 * device-service (consumer). Both services compile against this artifact, so an
 * incompatible change here is a breaking change for every consumer.</p>
 *
 * <p>The topic name lives in {@link #TOPIC} so that producer and consumer cannot
 * drift apart silently.</p>
 */
public final class OrderCancelledEvent {

    /** Kafka topic carrying this event; both the producer and the consumer reference it. */
    public static final String TOPIC = "order.cancelled";

    private final String orderId;
    private final String deviceId;
    private final String reason;
    private final Instant cancelledAt;

    public OrderCancelledEvent(String orderId, String deviceId, String reason, Instant cancelledAt) {
        this.orderId = Objects.requireNonNull(orderId, "orderId");
        this.deviceId = Objects.requireNonNull(deviceId, "deviceId");
        this.reason = reason == null ? "unspecified" : reason;
        this.cancelledAt = cancelledAt == null ? Instant.EPOCH : cancelledAt;
    }

    public String orderId() {
        return orderId;
    }

    public String deviceId() {
        return deviceId;
    }

    public String reason() {
        return reason;
    }

    public Instant cancelledAt() {
        return cancelledAt;
    }

    @Override
    public String toString() {
        return "OrderCancelledEvent{orderId='" + orderId + "', deviceId='" + deviceId
                + "', reason='" + reason + "', cancelledAt=" + cancelledAt + '}';
    }
}
JAVA

write_file "$COMMON/src/main/java/com/example/common/messaging/EventPublisher.java" <<'JAVA'
package com.example.common.messaging;

import com.example.common.event.OrderCancelledEvent;

/**
 * Transport-agnostic port for publishing domain events.
 *
 * <p>Services depend on this interface rather than on a broker client so that the
 * messaging transport can be replaced in tests.</p>
 */
public interface EventPublisher {

    /**
     * Publishes an event to an explicit topic.
     *
     * @param topic destination topic
     * @param event event payload
     * @param <T>   event type
     */
    <T> void publish(String topic, T event);

    /**
     * Publishes an event to the topic registered for its type.
     *
     * @param event event payload
     * @param <T>   event type
     */
    default <T> void publish(T event) {
        publish(topicFor(event), event);
    }

    /**
     * Resolves the topic that carries the given event type.
     *
     * @param event event payload
     * @return the destination topic
     */
    static String topicFor(Object event) {
        if (event instanceof OrderCancelledEvent) {
            return OrderCancelledEvent.TOPIC;
        }
        throw new IllegalArgumentException("no topic registered for " + event.getClass().getName());
    }
}
JAVA

write_file "$COMMON/README.md" <<'MD'
# common

Shared contract library for the example platform. Published to the internal Maven
repository as `com.example:common`.

## Responsibilities

- Domain event payloads shared between services, for example
  `com.example.common.event.OrderCancelledEvent`.
- Messaging ports (interfaces) that services depend on instead of a broker client,
  for example `com.example.common.messaging.EventPublisher`.
- Serialization-stable field names, because every consumer of an event reads them.

## Consumers

| Service | Declared version of `common` |
| --- | --- |
| `order-service` | `1.4.2` |
| `device-service` | `2.0.0` |

The released artifact in this repository is `1.4.2`. The `2.0.0` dependency declared by
`device-service` therefore does not exist here; that skew is intentional fixture data.

## Boundaries

This library has no service-specific logic, no Spring beans and no direct dependency on
a broker client. Anything that needs a running broker belongs in a service.
MD

commit_repo "$COMMON" 'feat: add shared order cancellation contract'

##############################################################################
# order-service - producer (kind: service)
##############################################################################

init_repo "$ORDER"

write_file "$ORDER/pom.xml" <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.4</version>
    <relativePath/>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>order-service</artifactId>
  <version>3.1.0</version>
  <packaging>jar</packaging>

  <name>order-service</name>
  <description>Order lifecycle service; publishes OrderCancelledEvent.</description>

  <properties>
    <java.version>17</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>common</artifactId>
      <version>1.4.2</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>
  </dependencies>
</project>
XML

write_file "$ORDER/src/main/java/com/example/order/Order.java" <<'JAVA'
package com.example.order;

import java.time.Instant;

/**
 * Aggregate root for a customer order.
 *
 * <p>An order is bound to at most one device; cancelling the order must therefore
 * release the reservation that device-service holds for it.</p>
 */
public final class Order {

    /** Lifecycle states of an order; only CREATED and CONFIRMED can be cancelled. */
    public enum State {
        CREATED,
        CONFIRMED,
        CANCELLED
    }

    private final String id;
    private final String deviceId;
    private State state;
    private Instant cancelledAt;

    public Order(String id, String deviceId, State state) {
        this.id = id;
        this.deviceId = deviceId;
        this.state = state;
    }

    public String id() {
        return id;
    }

    public String deviceId() {
        return deviceId;
    }

    public State state() {
        return state;
    }

    public Instant cancelledAt() {
        return cancelledAt;
    }

    /**
     * Rejects cancellation of an order that already reached the CANCELLED state.
     *
     * @throws IllegalStateException when the order is not cancellable
     */
    public void validateCancellable() {
        if (state == State.CANCELLED) {
            throw new IllegalStateException("order " + id + " is already cancelled");
        }
    }

    public void markCancelled(Instant when) {
        this.state = State.CANCELLED;
        this.cancelledAt = when;
    }
}
JAVA

write_file "$ORDER/src/main/java/com/example/order/OrderNotFoundException.java" <<'JAVA'
package com.example.order;

/** Raised when an order id cannot be resolved. */
public class OrderNotFoundException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    public OrderNotFoundException(String orderId) {
        super("order not found: " + orderId);
    }
}
JAVA

write_file "$ORDER/src/main/java/com/example/order/OrderRepository.java" <<'JAVA'
package com.example.order;

import java.util.Optional;

/** Persistence port for {@link Order} aggregates. */
public interface OrderRepository {

    Optional<Order> findById(String orderId);

    Order save(Order order);
}
JAVA

write_file "$ORDER/src/main/java/com/example/order/OrderService.java" <<'JAVA'
package com.example.order;

import com.example.common.event.OrderCancelledEvent;
import com.example.common.messaging.EventPublisher;
import java.time.Instant;
import java.util.Objects;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Cancellation use cases for order-service.
 *
 * <p>{@link #cancelOrder(String, String)} is the only producer of
 * {@link OrderCancelledEvent} in the platform: it validates the aggregate state,
 * persists the cancellation and then publishes the event that device-service
 * consumes in order to release the device reservation.</p>
 */
@Service
public class OrderService {

    private final OrderRepository orderRepository;
    private final EventPublisher eventPublisher;

    public OrderService(OrderRepository orderRepository, EventPublisher eventPublisher) {
        this.orderRepository = Objects.requireNonNull(orderRepository, "orderRepository");
        this.eventPublisher = Objects.requireNonNull(eventPublisher, "eventPublisher");
    }

    /**
     * Cancels an order and publishes {@link OrderCancelledEvent}.
     *
     * @param orderId identifier of the order to cancel
     * @param reason  free-text cancellation reason
     * @return the event that was published
     * @throws OrderNotFoundException when the order does not exist
     * @throws IllegalStateException  when the order is already cancelled
     */
    @Transactional
    public OrderCancelledEvent cancelOrder(String orderId, String reason) {
        Objects.requireNonNull(orderId, "orderId");

        Order order = orderRepository.findById(orderId)
                .orElseThrow(() -> new OrderNotFoundException(orderId));

        // State validation first: a terminal order must not be cancelled twice.
        order.validateCancellable();
        order.markCancelled(Instant.now());
        orderRepository.save(order);

        OrderCancelledEvent event = new OrderCancelledEvent(
                order.id(), order.deviceId(), reason, order.cancelledAt());
        eventPublisher.publish(OrderCancelledEvent.TOPIC, event);
        return event;
    }
}
JAVA

write_file "$ORDER/src/main/java/com/example/order/api/OrderCancelController.java" <<'JAVA'
package com.example.order.api;

import com.example.common.event.OrderCancelledEvent;
import com.example.order.OrderService;
import java.time.Instant;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

/** REST entry point for order cancellation. */
@RestController
public class OrderCancelController {

    private final OrderService orderService;

    public OrderCancelController(OrderService orderService) {
        this.orderService = orderService;
    }

    /**
     * {@code POST /orders/{id}/cancel}
     *
     * <p>Accepts the cancellation and returns the published event payload with 202,
     * because the device reservation is released asynchronously by device-service.</p>
     */
    @PostMapping(path = "/orders/{id}/cancel", consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CancelOrderResponse> cancelOrder(@PathVariable("id") String orderId,
                                                           @RequestBody CancelOrderRequest request) {
        OrderCancelledEvent event = orderService.cancelOrder(orderId, request.reason());
        CancelOrderResponse body = new CancelOrderResponse(
                event.orderId(), event.deviceId(), event.reason(), event.cancelledAt());
        return ResponseEntity.accepted().body(body);
    }

    /** Request body of {@code POST /orders/{id}/cancel}. */
    public record CancelOrderRequest(String reason) {
    }

    /** Response body of {@code POST /orders/{id}/cancel}. */
    public record CancelOrderResponse(String orderId, String deviceId, String reason, Instant cancelledAt) {
    }
}
JAVA

write_file "$ORDER/src/main/java/com/example/order/config/OrderEventProducerConfig.java" <<'JAVA'
package com.example.order.config;

import com.example.common.event.OrderCancelledEvent;
import java.util.HashMap;
import java.util.Map;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.StringSerializer;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.core.DefaultKafkaProducerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.core.ProducerFactory;
import org.springframework.kafka.support.serializer.JsonSerializer;

/**
 * Producer-side Kafka wiring for order-service.
 *
 * <p>order-service only writes to the bus: this module declares no message listener.
 * The consumer of {@link OrderCancelledEvent} lives in device-service, which
 * subscribes to {@link #ORDER_CANCELLED_TOPIC}.</p>
 */
@Configuration
public class OrderEventProducerConfig {

    /** Topic carrying {@link OrderCancelledEvent}; mirrors {@link OrderCancelledEvent#TOPIC}. */
    public static final String ORDER_CANCELLED_TOPIC = "order.cancelled";

    @Value("${spring.kafka.bootstrap-servers:kafka:9092}")
    private String bootstrapServers;

    @Bean
    public ProducerFactory<String, Object> orderProducerFactory() {
        Map<String, Object> props = new HashMap<>();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);
        props.put(ProducerConfig.ACKS_CONFIG, "all");
        props.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, Boolean.TRUE);
        return new DefaultKafkaProducerFactory<>(props);
    }

    @Bean
    public KafkaTemplate<String, Object> orderKafkaTemplate(ProducerFactory<String, Object> orderProducerFactory) {
        return new KafkaTemplate<>(orderProducerFactory);
    }
}
JAVA

write_file "$ORDER/src/main/resources/application.yml" <<'YAML'
spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
order:
  events:
    order-cancelled-topic: order.cancelled
YAML

write_file "$ORDER/README.md" <<'MD'
# order-service

Order lifecycle service. Owns orders, their state machine and the device binding
created when an order is confirmed.

## Responsibilities

- Expose `POST /orders/{id}/cancel` for customer and back-office cancellation.
- Validate order state before cancelling; an order that is already `CANCELLED` is
  rejected instead of being cancelled twice.
- Publish `com.example.common.event.OrderCancelledEvent` on the `order.cancelled`
  topic whenever a cancellation is accepted.

## Dependencies

- `com.example:common:1.4.2` - shared event payloads and the `EventPublisher` port.
- Spring Boot 3.3 web and Spring Kafka.

## Messaging

This service is a producer only. `OrderEventProducerConfig` wires the Kafka template
and names the `order.cancelled` topic; no message listener is declared in this
repository. The consumer side lives in `device-service`, which releases the device
reservation for the cancelled order.

## Known coupling

The `order.cancelled` topic is shared with `device-service`. A change to
`OrderCancelledEvent` (field names, nullability, the topic constant) changes the
contract for that service even though nothing here fails to compile.
MD

commit_repo "$ORDER" 'feat: cancel orders and publish OrderCancelledEvent'

write_file "$ORDER/src/main/java/com/example/order/OrderCancelAudit.java" <<'JAVA'
package com.example.order;

import java.time.Instant;
import java.util.Objects;

/**
 * Append-only audit record written when a cancellation request is accepted.
 *
 * <p>Introduced by the second commit of this fixture repository so that the
 * repository has real history: commit 1 is the initial service, commit 2 adds this
 * type.</p>
 */
public final class OrderCancelAudit {

    private final String orderId;
    private final String reason;
    private final Instant recordedAt;

    public OrderCancelAudit(String orderId, String reason, Instant recordedAt) {
        this.orderId = Objects.requireNonNull(orderId, "orderId");
        this.reason = reason;
        this.recordedAt = recordedAt;
    }

    public String orderId() {
        return orderId;
    }

    public String reason() {
        return reason;
    }

    public Instant recordedAt() {
        return recordedAt;
    }

    @Override
    public String toString() {
        return "OrderCancelAudit{orderId='" + orderId + "', reason='" + reason
                + "', recordedAt=" + recordedAt + '}';
    }
}
JAVA

commit_repo "$ORDER" 'feat: record an audit entry for accepted cancellations'

##############################################################################
# device-service - consumer (kind: service)
##############################################################################

init_repo "$DEVICE"

write_file "$DEVICE/pom.xml" <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.4</version>
    <relativePath/>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>device-service</artifactId>
  <version>2.5.0</version>
  <packaging>jar</packaging>

  <name>device-service</name>
  <description>Device inventory service; consumes OrderCancelledEvent.</description>

  <properties>
    <java.version>17</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>common</artifactId>
      <version>2.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>
  </dependencies>
</project>
XML

write_file "$DEVICE/src/main/java/com/example/device/DeviceReservation.java" <<'JAVA'
package com.example.device;

/**
 * A device held for an order until the order completes or is cancelled.
 */
public final class DeviceReservation {

    /** Lifecycle states of a reservation. */
    public enum State {
        HELD,
        RELEASED
    }

    private final String orderId;
    private final String deviceId;
    private State state;

    public DeviceReservation(String orderId, String deviceId, State state) {
        this.orderId = orderId;
        this.deviceId = deviceId;
        this.state = state;
    }

    public String orderId() {
        return orderId;
    }

    public String deviceId() {
        return deviceId;
    }

    public State state() {
        return state;
    }

    /**
     * Moves the reservation to RELEASED.
     *
     * @throws IllegalStateException when the reservation was already released
     */
    public void markReleased() {
        if (state == State.RELEASED) {
            throw new IllegalStateException("reservation for order " + orderId + " is already released");
        }
        this.state = State.RELEASED;
    }
}
JAVA

write_file "$DEVICE/src/main/java/com/example/device/DeviceReservationRepository.java" <<'JAVA'
package com.example.device;

import java.util.Optional;

/** Persistence port for {@link DeviceReservation} rows. */
public interface DeviceReservationRepository {

    Optional<DeviceReservation> findByOrderId(String orderId);

    DeviceReservation save(DeviceReservation reservation);
}
JAVA

write_file "$DEVICE/src/main/java/com/example/device/DeviceReservationService.java" <<'JAVA'
package com.example.device;

import java.util.Objects;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Releases device reservations.
 *
 * <p>{@link #releaseReservation(String, String, String)} is called by
 * {@link DeviceReservationConsumer} for every cancellation event that order-service
 * publishes on the order.cancelled topic.</p>
 */
@Service
public class DeviceReservationService {

    /** Attempts made before a failed release is parked for manual review. */
    public static final int RELEASE_RETRY_ATTEMPTS = 3;

    private final DeviceReservationRepository reservationRepository;

    public DeviceReservationService(DeviceReservationRepository reservationRepository) {
        this.reservationRepository = Objects.requireNonNull(reservationRepository, "reservationRepository");
    }

    /**
     * Frees the reservation held for the cancelled order.
     *
     * <p>Releasing an already released reservation is a no-op so that at-least-once
     * delivery of the cancellation event stays idempotent.</p>
     *
     * @param orderId  order whose reservation is released
     * @param deviceId device that was reserved for the order
     * @param reason   cancellation reason carried by the event
     */
    @Transactional
    public void releaseReservation(String orderId, String deviceId, String reason) {
        Objects.requireNonNull(orderId, "orderId");

        DeviceReservation reservation = reservationRepository.findByOrderId(orderId)
                .orElseThrow(() -> new IllegalStateException("no reservation for order " + orderId));

        if (reservation.state() == DeviceReservation.State.RELEASED) {
            return;
        }

        reservation.markReleased();
        reservationRepository.save(reservation);
    }
}
JAVA

write_file "$DEVICE/src/main/java/com/example/device/DeviceReservationConsumer.java" <<'JAVA'
package com.example.device;

import com.example.common.event.OrderCancelledEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Consumes {@link OrderCancelledEvent} messages published by order-service on the
 * {@link OrderCancelledEvent#TOPIC} topic and frees the device reservation that was
 * held for the cancelled order.
 */
@Component
public class DeviceReservationConsumer {

    private static final Logger LOG = LoggerFactory.getLogger(DeviceReservationConsumer.class);

    private final DeviceReservationService reservationService;

    public DeviceReservationConsumer(DeviceReservationService reservationService) {
        this.reservationService = reservationService;
    }

    /**
     * Handles an order cancellation coming from order-service.
     *
     * @param event cancellation payload shared through com.example:common
     */
    @KafkaListener(topics = OrderCancelledEvent.TOPIC, groupId = "${spring.kafka.consumer.group-id}")
    public void onOrderCancelled(OrderCancelledEvent event) {
        LOG.info("handling OrderCancelledEvent for order {} (device {})", event.orderId(), event.deviceId());
        reservationService.releaseReservation(event.orderId(), event.deviceId(), event.reason());
    }
}
JAVA

write_file "$DEVICE/src/main/resources/application.yml" <<'YAML'
spring:
  application:
    name: device-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: device-service-reservations
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.common.event
device:
  reservations:
    order-cancelled-topic: order.cancelled
YAML

write_file "$DEVICE/README.md" <<'MD'
# device-service

Owns the device inventory and the reservations that hold a device for an order.

## Responsibilities

- Track which device is reserved for which order.
- Consume `OrderCancelledEvent` from the `order.cancelled` topic and release the
  reservation for the cancelled order.
- Keep the release idempotent: at-least-once delivery must not fail a second release.

## Dependencies

- `com.example:common:2.0.0` - shared event payloads, including
  `com.example.common.event.OrderCancelledEvent`.
- Spring Boot 3.3 and Spring Kafka.

## Messaging

`DeviceReservationConsumer.onOrderCancelled(OrderCancelledEvent)` is the consumer
side of the cancellation flow whose producer lives in `order-service`. It calls
`DeviceReservationService.releaseReservation(...)`, which retries up to
`RELEASE_RETRY_ATTEMPTS` times before parking the reservation for manual review.

## Known coupling

The declared version of `common` (`2.0.0`) differs from the version `order-service`
compiles against (`1.4.2`). Both services exchange the same event type name, so the
payload must stay wire-compatible even while the declared artifact versions differ.
MD

commit_repo "$DEVICE" 'feat: release device reservations when orders are cancelled'

##############################################################################
# Uncommitted work: device-service must be the dirty repository
##############################################################################

# Tracked modification: bump the retry constant and document the change.
write_file "$DEVICE/src/main/java/com/example/device/DeviceReservationService.java" <<'JAVA'
package com.example.device;

import java.util.Objects;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Releases device reservations.
 *
 * <p>{@link #releaseReservation(String, String, String)} is called by
 * {@link DeviceReservationConsumer} for every cancellation event that order-service
 * publishes on the order.cancelled topic.</p>
 */
@Service
public class DeviceReservationService {

    /**
     * Attempts made before a failed release is parked for manual review.
     *
     * <p>Uncommitted fixture change: bumped from 3 to 5 so that a burst of
     * cancellations survives a short broker outage. This edit is deliberately left
     * uncommitted so the fixture exercises frozen dirty input.</p>
     */
    public static final int RELEASE_RETRY_ATTEMPTS = 5;

    private final DeviceReservationRepository reservationRepository;

    public DeviceReservationService(DeviceReservationRepository reservationRepository) {
        this.reservationRepository = Objects.requireNonNull(reservationRepository, "reservationRepository");
    }

    /**
     * Frees the reservation held for the cancelled order.
     *
     * <p>Releasing an already released reservation is a no-op so that at-least-once
     * delivery of the cancellation event stays idempotent.</p>
     *
     * @param orderId  order whose reservation is released
     * @param deviceId device that was reserved for the order
     * @param reason   cancellation reason carried by the event
     */
    @Transactional
    public void releaseReservation(String orderId, String deviceId, String reason) {
        Objects.requireNonNull(orderId, "orderId");

        DeviceReservation reservation = reservationRepository.findByOrderId(orderId)
                .orElseThrow(() -> new IllegalStateException("no reservation for order " + orderId));

        if (reservation.state() == DeviceReservation.State.RELEASED) {
            return;
        }

        reservation.markReleased();
        reservationRepository.save(reservation);
    }
}
JAVA

# Untracked new file: never added to the index.
write_file "$DEVICE/src/main/java/com/example/device/ReleaseRetryPolicy.java" <<'JAVA'
package com.example.device;

/**
 * Retry policy for reservation releases.
 *
 * <p>Untracked fixture file: it is written after the final commit and deliberately
 * left untracked so the knowledge library has to ingest uncommitted work-in-progress
 * source.</p>
 */
public final class ReleaseRetryPolicy {

    /** Maximum release attempts before the reservation is parked for manual review. */
    public static final int MAX_ATTEMPTS = 5;

    /** Base backoff between attempts, in milliseconds. */
    public static final long BACKOFF_MILLIS = 250L;

    private ReleaseRetryPolicy() {
    }

    /**
     * Exponential backoff for the given attempt number.
     *
     * @param attempt 1-based attempt number
     * @return milliseconds to wait before the next attempt
     */
    public static long backoffMillis(int attempt) {
        return BACKOFF_MILLIS * (1L << Math.max(0, attempt - 1));
    }
}
JAVA

##############################################################################
# Manifest
##############################################################################

emit_repo \
  'order-service' \
  'service' \
  'com.example:order-service:3.1.0' \
  'publishes OrderCancelledEvent on topic order.cancelled; depends on com.example:common:1.4.2'

emit_repo \
  'device-service' \
  'service' \
  'com.example:device-service:2.5.0' \
  'consumes OrderCancelledEvent from topic order.cancelled; depends on com.example:common:2.0.0'

emit_repo \
  'common' \
  'common' \
  'com.example:common:1.4.2' \
  'order-service depends on common 1.4.2 and device-service depends on common 2.0.0; the released artifact here is 1.4.2, so the 2.0.0 dependency is deliberate version skew'

write_file "$TARGET/README.md" <<'MD'
# knowledge-fixtures

Synthetic multi-repository Java fixture for the unified project knowledge library.

This directory is GENERATED. Do not edit it by hand; re-run the generator instead:

```bash
bash testdata/knowledge-fixtures/generate.sh [target-dir]
```

## Layout

| Path | Kind | Contents |
| --- | --- | --- |
| `order-service/` | service | Publishes `OrderCancelledEvent` to `order.cancelled`, depends on `com.example:common:1.4.2` |
| `device-service/` | service | Consumes `OrderCancelledEvent` and releases reservations, depends on `com.example:common:2.0.0`, carries uncommitted work |
| `common/` | common | Shared contracts and messaging ports, released as `com.example:common:1.4.2` |
| `fixture-manifest.json` | manifest | Recorded head commits, dirtiness and artifacts |

## Guarantees

- Deterministic: fixed author/committer identity, fixed timestamp and fixed messages,
  so repeated runs produce identical commit SHAs and identical manifests.
- Idempotent: the target directory is deleted and recreated on every run.
- `order-service` has two commits; a second commit adds `OrderCancelAudit`.
- `common` and `order-service` are clean; `device-service` is dirty with one modified
  tracked file and one untracked file.

## Synthetic material

This is fixture data. It is not derived from any production repository and must not be
treated as project truth.
MD

cat > "$TARGET/fixture-manifest.json" <<JSON
{
  "generated_at": "${FIXED_GENERATED_AT}",
  "notes": "${MANIFEST_NOTES}",
  "repos": [${MANIFEST_REPOS}
  ]
}
JSON

printf 'fixture written to %s\n' "$TARGET"
for repo_name in order-service device-service common; do
  repo_path="$TARGET/$repo_name"
  printf '  %-15s %s  branch=%s  commits=%s  dirty=%s\n' \
    "$repo_name" \
    "$(git -C "$repo_path" rev-parse HEAD)" \
    "$(git -C "$repo_path" rev-parse --abbrev-ref HEAD)" \
    "$(git -C "$repo_path" rev-list --count HEAD)" \
    "$(if [ -n "$(git -C "$repo_path" status --porcelain)" ]; then echo yes; else echo no; fi)"
done
